/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-west-1",
    "aws_storage_bucket": "yourappname-yourappenv-files123456-uploads",
    "aws_storage_region": "us-west-2"
};


export default awsmobile;
